### ISSUE TITLE
How should we structure the information in this repo?

### ISSUE THREAD

**Issue by johnpallett** [immersive-web/privacy-and-security#2]
One approach would be to create multiple explainers, each on a specific topic. This might make it easier for individual APIs to reference specific topics that are relevant.

Another approach would be to combine all the topics in this repo into a single explainer. That would make it easier for everyone to link to a comprehensive guide (instead of linking to multiple docs).

Any opinions or preferences?

For now, I'm adding issues for a few topics that I'd like to see covered; my assumption is that we can migrate the contents of those discussion threads into whatever explainer format makes sense.

**Comment by blairmacintyre** [comment]
I'm unsure ... let's see which issues get traction.

**Comment by johnpallett** [comment]
This topic was discussed in a meeting Sept 5 with Nell Waliczek, Diane Hosfelt, David Dorwin, Chris Wilso, Blair MacIntyre, Alex Turner, John Pallett. Decision was to create a single explainer encompassing the considerations (including threat vectors) and enumerating options for UAs to address those considerations (without prescribing specific solutions).
